/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as KidRouteImport } from './routes/kid'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as KidIndexRouteImport } from './routes/kid.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProRelatoriosRouteImport } from './routes/pro.relatorios'
import { Route as ProPacientesRouteImport } from './routes/pro.pacientes'
import { Route as ProObjetivosRouteImport } from './routes/pro.objetivos'
import { Route as ProMensagensRouteImport } from './routes/pro.mensagens'
import { Route as ProIndicadoresRouteImport } from './routes/pro.indicadores'
import { Route as ProIaRouteImport } from './routes/pro.ia'
import { Route as ProEvolucaoRouteImport } from './routes/pro.evolucao'
import { Route as ProEscolaRouteImport } from './routes/pro.escola'
import { Route as ProEscalasRouteImport } from './routes/pro.escalas'
import { Route as ProDocumentosRouteImport } from './routes/pro.documentos'
import { Route as ProConfiguracoesRouteImport } from './routes/pro.configuracoes'
import { Route as ProAgendaRouteImport } from './routes/pro.agenda'
import { Route as KidRespirarRouteImport } from './routes/kid.respirar'
import { Route as KidHumorRouteImport } from './routes/kid.humor'
import { Route as KidHistoriasRouteImport } from './routes/kid.historias'
import { Route as KidAzulRouteImport } from './routes/kid.azul'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppRotinasRouteImport } from './routes/app.rotinas'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppObjetivosRouteImport } from './routes/app.objetivos'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppMedicacaoRouteImport } from './routes/app.medicacao'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppHumorRouteImport } from './routes/app.humor'
import { Route as AppEscolaRouteImport } from './routes/app.escola'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppCriancaRouteImport } from './routes/app.crianca'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppComportamentoRouteImport } from './routes/app.comportamento'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfessionalsRouteImport } from './routes/admin.professionals'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMissionsRouteImport } from './routes/admin.missions'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminFamiliesRouteImport } from './routes/admin.families'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminChildrenRouteImport } from './routes/admin.children'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAchievementsRouteImport } from './routes/admin.achievements'
import { Route as ProSessoesNovaRouteImport } from './routes/pro.sessoes.nova'
import { Route as ProSessoesIdRouteImport } from './routes/pro.sessoes.$id'
import { Route as ProPacientesChildIdRouteImport } from './routes/pro.pacientes.$childId'
import { Route as ApiReportsWeeklyRouteImport } from './routes/api/reports.weekly'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const KidRoute = KidRouteImport.update({
  id: '/kid',
  path: '/kid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const KidIndexRoute = KidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KidRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProRelatoriosRoute = ProRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => ProRoute,
} as any)
const ProPacientesRoute = ProPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => ProRoute,
} as any)
const ProObjetivosRoute = ProObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => ProRoute,
} as any)
const ProMensagensRoute = ProMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => ProRoute,
} as any)
const ProIndicadoresRoute = ProIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => ProRoute,
} as any)
const ProIaRoute = ProIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => ProRoute,
} as any)
const ProEvolucaoRoute = ProEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => ProRoute,
} as any)
const ProEscolaRoute = ProEscolaRouteImport.update({
  id: '/escola',
  path: '/escola',
  getParentRoute: () => ProRoute,
} as any)
const ProEscalasRoute = ProEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => ProRoute,
} as any)
const ProDocumentosRoute = ProDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => ProRoute,
} as any)
const ProConfiguracoesRoute = ProConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ProRoute,
} as any)
const ProAgendaRoute = ProAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProRoute,
} as any)
const KidRespirarRoute = KidRespirarRouteImport.update({
  id: '/respirar',
  path: '/respirar',
  getParentRoute: () => KidRoute,
} as any)
const KidHumorRoute = KidHumorRouteImport.update({
  id: '/humor',
  path: '/humor',
  getParentRoute: () => KidRoute,
} as any)
const KidHistoriasRoute = KidHistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => KidRoute,
} as any)
const KidAzulRoute = KidAzulRouteImport.update({
  id: '/azul',
  path: '/azul',
  getParentRoute: () => KidRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppRotinasRoute = AppRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppObjetivosRoute = AppObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicacaoRoute = AppMedicacaoRouteImport.update({
  id: '/medicacao',
  path: '/medicacao',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppHumorRoute = AppHumorRouteImport.update({
  id: '/humor',
  path: '/humor',
  getParentRoute: () => AppRoute,
} as any)
const AppEscolaRoute = AppEscolaRouteImport.update({
  id: '/escola',
  path: '/escola',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppCriancaRoute = AppCriancaRouteImport.update({
  id: '/crianca',
  path: '/crianca',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComportamentoRoute = AppComportamentoRouteImport.update({
  id: '/comportamento',
  path: '/comportamento',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessionalsRoute = AdminProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsRoute = AdminMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFamiliesRoute = AdminFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChildrenRoute = AdminChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRoute,
} as any)
const ProSessoesNovaRoute = ProSessoesNovaRouteImport.update({
  id: '/sessoes/nova',
  path: '/sessoes/nova',
  getParentRoute: () => ProRoute,
} as any)
const ProSessoesIdRoute = ProSessoesIdRouteImport.update({
  id: '/sessoes/$id',
  path: '/sessoes/$id',
  getParentRoute: () => ProRoute,
} as any)
const ProPacientesChildIdRoute = ProPacientesChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => ProPacientesRoute,
} as any)
const ApiReportsWeeklyRoute = ApiReportsWeeklyRouteImport.update({
  id: '/api/reports/weekly',
  path: '/api/reports/weekly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/kid': typeof KidRouteWithChildren
  '/pro': typeof ProRouteWithChildren
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/families': typeof AdminFamiliesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/comportamento': typeof AppComportamentoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crianca': typeof AppCriancaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/escola': typeof AppEscolaRoute
  '/app/humor': typeof AppHumorRoute
  '/app/ia': typeof AppIaRoute
  '/app/medicacao': typeof AppMedicacaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/objetivos': typeof AppObjetivosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/rotinas': typeof AppRotinasRoute
  '/app/timeline': typeof AppTimelineRoute
  '/kid/azul': typeof KidAzulRoute
  '/kid/historias': typeof KidHistoriasRoute
  '/kid/humor': typeof KidHumorRoute
  '/kid/respirar': typeof KidRespirarRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/configuracoes': typeof ProConfiguracoesRoute
  '/pro/documentos': typeof ProDocumentosRoute
  '/pro/escalas': typeof ProEscalasRoute
  '/pro/escola': typeof ProEscolaRoute
  '/pro/evolucao': typeof ProEvolucaoRoute
  '/pro/ia': typeof ProIaRoute
  '/pro/indicadores': typeof ProIndicadoresRoute
  '/pro/mensagens': typeof ProMensagensRoute
  '/pro/objetivos': typeof ProObjetivosRoute
  '/pro/pacientes': typeof ProPacientesRouteWithChildren
  '/pro/relatorios': typeof ProRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/kid/': typeof KidIndexRoute
  '/pro/': typeof ProIndexRoute
  '/api/reports/weekly': typeof ApiReportsWeeklyRoute
  '/pro/pacientes/$childId': typeof ProPacientesChildIdRoute
  '/pro/sessoes/$id': typeof ProSessoesIdRoute
  '/pro/sessoes/nova': typeof ProSessoesNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/families': typeof AdminFamiliesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/comportamento': typeof AppComportamentoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crianca': typeof AppCriancaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/escola': typeof AppEscolaRoute
  '/app/humor': typeof AppHumorRoute
  '/app/ia': typeof AppIaRoute
  '/app/medicacao': typeof AppMedicacaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/objetivos': typeof AppObjetivosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/rotinas': typeof AppRotinasRoute
  '/app/timeline': typeof AppTimelineRoute
  '/kid/azul': typeof KidAzulRoute
  '/kid/historias': typeof KidHistoriasRoute
  '/kid/humor': typeof KidHumorRoute
  '/kid/respirar': typeof KidRespirarRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/configuracoes': typeof ProConfiguracoesRoute
  '/pro/documentos': typeof ProDocumentosRoute
  '/pro/escalas': typeof ProEscalasRoute
  '/pro/escola': typeof ProEscolaRoute
  '/pro/evolucao': typeof ProEvolucaoRoute
  '/pro/ia': typeof ProIaRoute
  '/pro/indicadores': typeof ProIndicadoresRoute
  '/pro/mensagens': typeof ProMensagensRoute
  '/pro/objetivos': typeof ProObjetivosRoute
  '/pro/pacientes': typeof ProPacientesRouteWithChildren
  '/pro/relatorios': typeof ProRelatoriosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/kid': typeof KidIndexRoute
  '/pro': typeof ProIndexRoute
  '/api/reports/weekly': typeof ApiReportsWeeklyRoute
  '/pro/pacientes/$childId': typeof ProPacientesChildIdRoute
  '/pro/sessoes/$id': typeof ProSessoesIdRoute
  '/pro/sessoes/nova': typeof ProSessoesNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/kid': typeof KidRouteWithChildren
  '/pro': typeof ProRouteWithChildren
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/families': typeof AdminFamiliesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/comportamento': typeof AppComportamentoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crianca': typeof AppCriancaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/escola': typeof AppEscolaRoute
  '/app/humor': typeof AppHumorRoute
  '/app/ia': typeof AppIaRoute
  '/app/medicacao': typeof AppMedicacaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/objetivos': typeof AppObjetivosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/rotinas': typeof AppRotinasRoute
  '/app/timeline': typeof AppTimelineRoute
  '/kid/azul': typeof KidAzulRoute
  '/kid/historias': typeof KidHistoriasRoute
  '/kid/humor': typeof KidHumorRoute
  '/kid/respirar': typeof KidRespirarRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/configuracoes': typeof ProConfiguracoesRoute
  '/pro/documentos': typeof ProDocumentosRoute
  '/pro/escalas': typeof ProEscalasRoute
  '/pro/escola': typeof ProEscolaRoute
  '/pro/evolucao': typeof ProEvolucaoRoute
  '/pro/ia': typeof ProIaRoute
  '/pro/indicadores': typeof ProIndicadoresRoute
  '/pro/mensagens': typeof ProMensagensRoute
  '/pro/objetivos': typeof ProObjetivosRoute
  '/pro/pacientes': typeof ProPacientesRouteWithChildren
  '/pro/relatorios': typeof ProRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/kid/': typeof KidIndexRoute
  '/pro/': typeof ProIndexRoute
  '/api/reports/weekly': typeof ApiReportsWeeklyRoute
  '/pro/pacientes/$childId': typeof ProPacientesChildIdRoute
  '/pro/sessoes/$id': typeof ProSessoesIdRoute
  '/pro/sessoes/nova': typeof ProSessoesNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/kid'
    | '/pro'
    | '/admin/achievements'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/children'
    | '/admin/cms'
    | '/admin/community'
    | '/admin/coupons'
    | '/admin/families'
    | '/admin/finance'
    | '/admin/flags'
    | '/admin/games'
    | '/admin/logs'
    | '/admin/marketplace'
    | '/admin/missions'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/professionals'
    | '/admin/reports'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/chat'
    | '/app/calendario'
    | '/app/comportamento'
    | '/app/configuracoes'
    | '/app/crianca'
    | '/app/documentos'
    | '/app/escola'
    | '/app/humor'
    | '/app/ia'
    | '/app/medicacao'
    | '/app/notificacoes'
    | '/app/objetivos'
    | '/app/relatorios'
    | '/app/rotinas'
    | '/app/timeline'
    | '/kid/azul'
    | '/kid/historias'
    | '/kid/humor'
    | '/kid/respirar'
    | '/pro/agenda'
    | '/pro/configuracoes'
    | '/pro/documentos'
    | '/pro/escalas'
    | '/pro/escola'
    | '/pro/evolucao'
    | '/pro/ia'
    | '/pro/indicadores'
    | '/pro/mensagens'
    | '/pro/objetivos'
    | '/pro/pacientes'
    | '/pro/relatorios'
    | '/admin/'
    | '/app/'
    | '/kid/'
    | '/pro/'
    | '/api/reports/weekly'
    | '/pro/pacientes/$childId'
    | '/pro/sessoes/$id'
    | '/pro/sessoes/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/achievements'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/children'
    | '/admin/cms'
    | '/admin/community'
    | '/admin/coupons'
    | '/admin/families'
    | '/admin/finance'
    | '/admin/flags'
    | '/admin/games'
    | '/admin/logs'
    | '/admin/marketplace'
    | '/admin/missions'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/professionals'
    | '/admin/reports'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/chat'
    | '/app/calendario'
    | '/app/comportamento'
    | '/app/configuracoes'
    | '/app/crianca'
    | '/app/documentos'
    | '/app/escola'
    | '/app/humor'
    | '/app/ia'
    | '/app/medicacao'
    | '/app/notificacoes'
    | '/app/objetivos'
    | '/app/relatorios'
    | '/app/rotinas'
    | '/app/timeline'
    | '/kid/azul'
    | '/kid/historias'
    | '/kid/humor'
    | '/kid/respirar'
    | '/pro/agenda'
    | '/pro/configuracoes'
    | '/pro/documentos'
    | '/pro/escalas'
    | '/pro/escola'
    | '/pro/evolucao'
    | '/pro/ia'
    | '/pro/indicadores'
    | '/pro/mensagens'
    | '/pro/objetivos'
    | '/pro/pacientes'
    | '/pro/relatorios'
    | '/admin'
    | '/app'
    | '/kid'
    | '/pro'
    | '/api/reports/weekly'
    | '/pro/pacientes/$childId'
    | '/pro/sessoes/$id'
    | '/pro/sessoes/nova'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/kid'
    | '/pro'
    | '/admin/achievements'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/children'
    | '/admin/cms'
    | '/admin/community'
    | '/admin/coupons'
    | '/admin/families'
    | '/admin/finance'
    | '/admin/flags'
    | '/admin/games'
    | '/admin/logs'
    | '/admin/marketplace'
    | '/admin/missions'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/professionals'
    | '/admin/reports'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/chat'
    | '/app/calendario'
    | '/app/comportamento'
    | '/app/configuracoes'
    | '/app/crianca'
    | '/app/documentos'
    | '/app/escola'
    | '/app/humor'
    | '/app/ia'
    | '/app/medicacao'
    | '/app/notificacoes'
    | '/app/objetivos'
    | '/app/relatorios'
    | '/app/rotinas'
    | '/app/timeline'
    | '/kid/azul'
    | '/kid/historias'
    | '/kid/humor'
    | '/kid/respirar'
    | '/pro/agenda'
    | '/pro/configuracoes'
    | '/pro/documentos'
    | '/pro/escalas'
    | '/pro/escola'
    | '/pro/evolucao'
    | '/pro/ia'
    | '/pro/indicadores'
    | '/pro/mensagens'
    | '/pro/objetivos'
    | '/pro/pacientes'
    | '/pro/relatorios'
    | '/admin/'
    | '/app/'
    | '/kid/'
    | '/pro/'
    | '/api/reports/weekly'
    | '/pro/pacientes/$childId'
    | '/pro/sessoes/$id'
    | '/pro/sessoes/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  KidRoute: typeof KidRouteWithChildren
  ProRoute: typeof ProRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiReportsWeeklyRoute: typeof ApiReportsWeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid': {
      id: '/kid'
      path: '/kid'
      fullPath: '/kid'
      preLoaderRoute: typeof KidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/kid/': {
      id: '/kid/'
      path: '/'
      fullPath: '/kid/'
      preLoaderRoute: typeof KidIndexRouteImport
      parentRoute: typeof KidRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pro/relatorios': {
      id: '/pro/relatorios'
      path: '/relatorios'
      fullPath: '/pro/relatorios'
      preLoaderRoute: typeof ProRelatoriosRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/pacientes': {
      id: '/pro/pacientes'
      path: '/pacientes'
      fullPath: '/pro/pacientes'
      preLoaderRoute: typeof ProPacientesRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/objetivos': {
      id: '/pro/objetivos'
      path: '/objetivos'
      fullPath: '/pro/objetivos'
      preLoaderRoute: typeof ProObjetivosRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/mensagens': {
      id: '/pro/mensagens'
      path: '/mensagens'
      fullPath: '/pro/mensagens'
      preLoaderRoute: typeof ProMensagensRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/indicadores': {
      id: '/pro/indicadores'
      path: '/indicadores'
      fullPath: '/pro/indicadores'
      preLoaderRoute: typeof ProIndicadoresRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/ia': {
      id: '/pro/ia'
      path: '/ia'
      fullPath: '/pro/ia'
      preLoaderRoute: typeof ProIaRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/evolucao': {
      id: '/pro/evolucao'
      path: '/evolucao'
      fullPath: '/pro/evolucao'
      preLoaderRoute: typeof ProEvolucaoRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/escola': {
      id: '/pro/escola'
      path: '/escola'
      fullPath: '/pro/escola'
      preLoaderRoute: typeof ProEscolaRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/escalas': {
      id: '/pro/escalas'
      path: '/escalas'
      fullPath: '/pro/escalas'
      preLoaderRoute: typeof ProEscalasRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/documentos': {
      id: '/pro/documentos'
      path: '/documentos'
      fullPath: '/pro/documentos'
      preLoaderRoute: typeof ProDocumentosRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/configuracoes': {
      id: '/pro/configuracoes'
      path: '/configuracoes'
      fullPath: '/pro/configuracoes'
      preLoaderRoute: typeof ProConfiguracoesRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/agenda': {
      id: '/pro/agenda'
      path: '/agenda'
      fullPath: '/pro/agenda'
      preLoaderRoute: typeof ProAgendaRouteImport
      parentRoute: typeof ProRoute
    }
    '/kid/respirar': {
      id: '/kid/respirar'
      path: '/respirar'
      fullPath: '/kid/respirar'
      preLoaderRoute: typeof KidRespirarRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/humor': {
      id: '/kid/humor'
      path: '/humor'
      fullPath: '/kid/humor'
      preLoaderRoute: typeof KidHumorRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/historias': {
      id: '/kid/historias'
      path: '/historias'
      fullPath: '/kid/historias'
      preLoaderRoute: typeof KidHistoriasRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/azul': {
      id: '/kid/azul'
      path: '/azul'
      fullPath: '/kid/azul'
      preLoaderRoute: typeof KidAzulRouteImport
      parentRoute: typeof KidRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rotinas': {
      id: '/app/rotinas'
      path: '/rotinas'
      fullPath: '/app/rotinas'
      preLoaderRoute: typeof AppRotinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/objetivos': {
      id: '/app/objetivos'
      path: '/objetivos'
      fullPath: '/app/objetivos'
      preLoaderRoute: typeof AppObjetivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medicacao': {
      id: '/app/medicacao'
      path: '/medicacao'
      fullPath: '/app/medicacao'
      preLoaderRoute: typeof AppMedicacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/humor': {
      id: '/app/humor'
      path: '/humor'
      fullPath: '/app/humor'
      preLoaderRoute: typeof AppHumorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escola': {
      id: '/app/escola'
      path: '/escola'
      fullPath: '/app/escola'
      preLoaderRoute: typeof AppEscolaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crianca': {
      id: '/app/crianca'
      path: '/crianca'
      fullPath: '/app/crianca'
      preLoaderRoute: typeof AppCriancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comportamento': {
      id: '/app/comportamento'
      path: '/comportamento'
      fullPath: '/app/comportamento'
      preLoaderRoute: typeof AppComportamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professionals': {
      id: '/admin/professionals'
      path: '/professionals'
      fullPath: '/admin/professionals'
      preLoaderRoute: typeof AdminProfessionalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions': {
      id: '/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AdminMissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/families': {
      id: '/admin/families'
      path: '/families'
      fullPath: '/admin/families'
      preLoaderRoute: typeof AdminFamiliesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/children': {
      id: '/admin/children'
      path: '/children'
      fullPath: '/admin/children'
      preLoaderRoute: typeof AdminChildrenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pro/sessoes/nova': {
      id: '/pro/sessoes/nova'
      path: '/sessoes/nova'
      fullPath: '/pro/sessoes/nova'
      preLoaderRoute: typeof ProSessoesNovaRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/sessoes/$id': {
      id: '/pro/sessoes/$id'
      path: '/sessoes/$id'
      fullPath: '/pro/sessoes/$id'
      preLoaderRoute: typeof ProSessoesIdRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/pacientes/$childId': {
      id: '/pro/pacientes/$childId'
      path: '/$childId'
      fullPath: '/pro/pacientes/$childId'
      preLoaderRoute: typeof ProPacientesChildIdRouteImport
      parentRoute: typeof ProPacientesRoute
    }
    '/api/reports/weekly': {
      id: '/api/reports/weekly'
      path: '/api/reports/weekly'
      fullPath: '/api/reports/weekly'
      preLoaderRoute: typeof ApiReportsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminChildrenRoute: typeof AdminChildrenRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminFamiliesRoute: typeof AdminFamiliesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminMissionsRoute: typeof AdminMissionsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminProfessionalsRoute: typeof AdminProfessionalsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchoolsRoute: typeof AdminSchoolsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminChildrenRoute: AdminChildrenRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminFamiliesRoute: AdminFamiliesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminMissionsRoute: AdminMissionsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminProfessionalsRoute: AdminProfessionalsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSchoolsRoute: AdminSchoolsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppComportamentoRoute: typeof AppComportamentoRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCriancaRoute: typeof AppCriancaRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEscolaRoute: typeof AppEscolaRoute
  AppHumorRoute: typeof AppHumorRoute
  AppIaRoute: typeof AppIaRoute
  AppMedicacaoRoute: typeof AppMedicacaoRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppObjetivosRoute: typeof AppObjetivosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRotinasRoute: typeof AppRotinasRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppComportamentoRoute: AppComportamentoRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCriancaRoute: AppCriancaRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEscolaRoute: AppEscolaRoute,
  AppHumorRoute: AppHumorRoute,
  AppIaRoute: AppIaRoute,
  AppMedicacaoRoute: AppMedicacaoRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppObjetivosRoute: AppObjetivosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRotinasRoute: AppRotinasRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface KidRouteChildren {
  KidAzulRoute: typeof KidAzulRoute
  KidHistoriasRoute: typeof KidHistoriasRoute
  KidHumorRoute: typeof KidHumorRoute
  KidRespirarRoute: typeof KidRespirarRoute
  KidIndexRoute: typeof KidIndexRoute
}

const KidRouteChildren: KidRouteChildren = {
  KidAzulRoute: KidAzulRoute,
  KidHistoriasRoute: KidHistoriasRoute,
  KidHumorRoute: KidHumorRoute,
  KidRespirarRoute: KidRespirarRoute,
  KidIndexRoute: KidIndexRoute,
}

const KidRouteWithChildren = KidRoute._addFileChildren(KidRouteChildren)

interface ProPacientesRouteChildren {
  ProPacientesChildIdRoute: typeof ProPacientesChildIdRoute
}

const ProPacientesRouteChildren: ProPacientesRouteChildren = {
  ProPacientesChildIdRoute: ProPacientesChildIdRoute,
}

const ProPacientesRouteWithChildren = ProPacientesRoute._addFileChildren(
  ProPacientesRouteChildren,
)

interface ProRouteChildren {
  ProAgendaRoute: typeof ProAgendaRoute
  ProConfiguracoesRoute: typeof ProConfiguracoesRoute
  ProDocumentosRoute: typeof ProDocumentosRoute
  ProEscalasRoute: typeof ProEscalasRoute
  ProEscolaRoute: typeof ProEscolaRoute
  ProEvolucaoRoute: typeof ProEvolucaoRoute
  ProIaRoute: typeof ProIaRoute
  ProIndicadoresRoute: typeof ProIndicadoresRoute
  ProMensagensRoute: typeof ProMensagensRoute
  ProObjetivosRoute: typeof ProObjetivosRoute
  ProPacientesRoute: typeof ProPacientesRouteWithChildren
  ProRelatoriosRoute: typeof ProRelatoriosRoute
  ProIndexRoute: typeof ProIndexRoute
  ProSessoesIdRoute: typeof ProSessoesIdRoute
  ProSessoesNovaRoute: typeof ProSessoesNovaRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProAgendaRoute: ProAgendaRoute,
  ProConfiguracoesRoute: ProConfiguracoesRoute,
  ProDocumentosRoute: ProDocumentosRoute,
  ProEscalasRoute: ProEscalasRoute,
  ProEscolaRoute: ProEscolaRoute,
  ProEvolucaoRoute: ProEvolucaoRoute,
  ProIaRoute: ProIaRoute,
  ProIndicadoresRoute: ProIndicadoresRoute,
  ProMensagensRoute: ProMensagensRoute,
  ProObjetivosRoute: ProObjetivosRoute,
  ProPacientesRoute: ProPacientesRouteWithChildren,
  ProRelatoriosRoute: ProRelatoriosRoute,
  ProIndexRoute: ProIndexRoute,
  ProSessoesIdRoute: ProSessoesIdRoute,
  ProSessoesNovaRoute: ProSessoesNovaRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  KidRoute: KidRouteWithChildren,
  ProRoute: ProRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiReportsWeeklyRoute: ApiReportsWeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
